# Assignment 5

In [56]:
import pandas as pd
import numpy as np

# Load your original heart attack dataset
heart_attack= pd.read_csv("../data/heart_attack_risk_dataset.csv")

# Load the new obesity dataset
obesity= pd.read_csv("../data/Obesity prediction.csv")

In [58]:
heart_attack.head(10)

,Age,Gender,Smoking,Alcohol_Consumption,Physical_Activity_Level,BMI,Diabetes,Hypertension,Cholesterol_Level,Resting_BP,Heart_Rate,Family_History,Stress_Level,Chest_Pain_Type,Thalassemia,Fasting_Blood_Sugar,ECG_Results,Exercise_Induced_Angina,Max_Heart_Rate_Achieved,Heart_Attack_Risk
0,69,Female,1,0,Moderate,34.61,1,0,152.1,171,85,0,Moderate,Non-anginal,Reversible defect,0,Normal,0,114,Low
1,32,Male,0,0,Moderate,22.75,0,0,166.8,126,103,0,Low,Asymptomatic,Normal,0,ST-T abnormality,0,173,Moderate
2,89,Male,0,1,Moderate,35.32,0,0,272.3,123,127,0,Low,Typical,Reversible defect,0,ST-T abnormality,0,109,Low
3,78,Male,0,1,Moderate,18.23,1,0,237.7,144,125,0,Low,Typical,Fixed defect,1,Left Ventricular Hypertrophy,0,129,Low
4,38,Female,1,0,Moderate,19.82,0,0,207.7,123,107,0,High,Asymptomatic,Reversible defect,0,ST-T abnormality,0,124,Moderate
5,41,Male,0,1,Moderate,36.11,0,0,271.2,141,119,0,Low,Atypical,Fixed defect,0,Normal,0,101,High
6,20,Male,1,0,Low,15.12,0,0,164.8,154,67,0,Low,Non-anginal,Normal,0,Normal,0,176,Low
7,39,Female,0,0,Moderate,20.78,0,0,297.0,91,112,0,Low,Atypical,Normal,0,ST-T abnormality,1,134,Moderate
8,70,Male,0,1,High,29.20,0,0,280.7,121,71,0,Moderate,Non-anginal,Fixed defect,0,ST-T abnormality,0,168,Moderate
9,19,Female,0,0,High,35.54,0,1,275.0,167,76,0,Low,Typical,Reversible defect,1,Left Ventricular Hypertrophy,0,102,Moderate

In [60]:
heart_attack.dtypes

Age                          int64
Gender                      object
Smoking                      int64
Alcohol_Consumption          int64
Physical_Activity_Level     object
BMI                        float64
Diabetes                     int64
Hypertension                 int64
Cholesterol_Level          float64
Resting_BP                   int64
Heart_Rate                   int64
Family_History               int64
Stress_Level                object
Chest_Pain_Type             object
Thalassemia                 object
Fasting_Blood_Sugar          int64
ECG_Results                 object
Exercise_Induced_Angina      int64
Max_Heart_Rate_Achieved      int64
Heart_Attack_Risk           object
dtype: object

In [99]:
heart_attack.describe()

,Age,Smoking,Alcohol_Consumption,BMI,Diabetes,Hypertension,Cholesterol_Level,Resting_BP,Heart_Rate,Family_History,Fasting_Blood_Sugar,Exercise_Induced_Angina,Max_Heart_Rate_Achieved
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000
mean,53.398700,0.298420,0.401980,27.519357,0.198840,0.29738,225.036444,134.434100,94.530480,0.30034,0.149360,0.201640,149.305340
std,20.799006,0.457569,0.490303,7.225176,0.399131,0.45711,43.317373,25.907961,20.187124,0.45841,0.356447,0.401229,28.823699
min,18.000000,0.000000,0.000000,15.000000,0.000000,0.00000,150.000000,90.000000,60.000000,0.00000,0.000000,0.000000,100.000000
25%,35.000000,0.000000,0.000000,21.270000,0.000000,0.00000,187.300000,112.000000,77.000000,0.00000,0.000000,0.000000,124.000000
50%,53.000000,0.000000,0.000000,27.540000,0.000000,0.00000,225.100000,134.000000,94.000000,0.00000,0.000000,0.000000,149.000000
75%,71.000000,1.000000,1.000000,33.770000,0.000000,1.00000,262.600000,157.000000,112.000000,1.00000,0.000000,0.000000,174.000000
max,89.000000,1.000000,1.000000,40.000000,1.000000,1.00000,300.000000,179.000000,129.000000,1.00000,1.000000,1.000000,199.000000

In [62]:
obesity.head(10)

,Gender,Age,Height,Weight,Family_History,FAVC,FCVC,NCP,CAEC,Smoking,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight

In [101]:
obesity.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,23.972525,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.308664,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.000000,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.000000,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [64]:
obesity.dtypes

Gender             object
Age               float64
Height            float64
Weight            float64
Family_History     object
FAVC               object
FCVC              float64
NCP               float64
CAEC               object
Smoking            object
CH2O              float64
SCC                object
FAF               float64
TUE               float64
CALC               object
MTRANS             object
Obesity            object
dtype: object

In [78]:
# Use the pandas.DataFrame.astype(<type>) function to manipulate column dtypes.
# https://stackoverflow.com/questions/21291259/convert-floats-to-ints-in-pandas

obesity['Age'] = obesity['Age'].astype(int)

In [84]:
obesity.dtypes

Gender             object
Age                 int32
Height            float64
Weight            float64
Family_History     object
FAVC               object
FCVC              float64
NCP               float64
CAEC               object
Smoking            object
CH2O              float64
SCC                object
FAF               float64
TUE               float64
CALC               object
MTRANS             object
Obesity            object
dtype: object

In [95]:
# Merge the datasets on Age and Gender
merged_df = heart_attack.merge(obesity, on=["Age","Gender"], how="inner")  

# Display the first few rows of the merged dataset
merged_df.head(50)

,Age,Gender,Smoking_x,Alcohol_Consumption,Physical_Activity_Level,BMI,Diabetes,Hypertension,Cholesterol_Level,Resting_BP,...,NCP,CAEC,Smoking_y,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,3.000000,Sometimes,no,3.000000,no,0.000000,2.000000,no,Automobile,Obesity_Type_II
1,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,2.110937,Sometimes,no,2.175632,no,1.000000,0.000000,Sometimes,Walking,Overweight_Level_II
2,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,1.863012,Sometimes,no,2.196471,no,1.000000,0.000000,Sometimes,Automobile,Overweight_Level_II
3,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,3.053598,Sometimes,no,1.919629,no,0.408023,0.000000,no,Automobile,Overweight_Level_II
4,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,1.795580,Sometimes,no,1.855054,no,1.083572,0.218574,Sometimes,Public_Transportation,Overweight_Level_II
5,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,1.734762,Sometimes,no,2.600238,no,2.113992,0.584755,Sometimes,Automobile,Obesity_Type_I
6,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,2.129909,Sometimes,no,1.000000,no,1.989316,0.000000,no,Public_Transportation,Obesity_Type_II
7,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,1.924168,Sometimes,no,1.000000,no,1.622055,0.069367,no,Public_Transportation,Obesity_Type_II
8,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,2.175153,Sometimes,no,1.000000,no,1.985536,0.000000,no,Public_Transportation,Obesity_Type_II
9,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,3.000000,Sometimes,no,2.530035,no,0.955317,1.339232,Sometimes,Automobile,Obesity_Type_II
10,32,Male,0,0,Moderate,22.75,0,0,166.8,126,...,2.015675,Sometimes,no,1.000000,no,1.977918,0.056351,no,Public_Transportation,Obesity_Type_II
11,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
12,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,1.000000,Always,yes,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Overweight_Level_I
13,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,2.000000,no,2.000000,0.000000,no,Public_Transportation,Normal_Weight
14,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,1.000000,no,2.000000,1.000000,Frequently,Automobile,Normal_Weight
15,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,2.972426,no,2.160790,0.305954,Sometimes,Automobile,Overweight_Level_I
16,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.058539,Sometimes,no,1.130079,no,2.834373,0.044954,Sometimes,Automobile,Overweight_Level_I
17,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,2.965494,Sometimes,no,2.868132,no,0.000000,0.549250,Sometimes,Automobile,Overweight_Level_I
18,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,2.526775,no,0.271174,0.806069,Sometimes,Automobile,Overweight_Level_I
19,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,2.981604,no,0.000000,0.000000,no,Automobile,Overweight_Level_II
20,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,1.029798,no,0.000000,0.000000,no,Automobile,Overweight_Level_II
21,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,2.503198,no,0.000000,0.000000,no,Automobile,Overweight_Level_II
22,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,2.166024,no,0.000000,0.000000,no,Automobile,Overweight_Level_II
23,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,1.274774,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
24,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,1.169173,Sometimes,no,1.972551,no,1.903338,0.000000,Sometimes,Automobile,Obesity_Type_I
25,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,1.084442,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
26,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,1.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
27,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,1.440629,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
28,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,1.135278,Sometimes,no,1.399629,no,1.648883,0.000000,Sometimes,Automobile,Obesity_Type_I
29,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,1.130751,Sometimes,no,1.385175,no,1.666965,0.000000,Sometimes,Automobile,Obesity_Type_I
30,38,Female,1,0,Moderate,19.82,0,0,207.7,123,...,3.000000,Sometimes,no,1.095134,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
31,41,Male,0,1,Moderate,36.11,0,0,271.2,141,...,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Automobile,Obesity_Type_I
32,41,Male,0,1,Moderate,36.11,0,0,271.2,141,...,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Bike,Obesity_Type_II
33,41,Male,0,1,Moderate,36.11,0,0,271.2,141,...,1.000000,Sometimes,no,1.000000,no,1.000000,0.000000,Frequently,Automobile,Obesity_Type_II
34,41,Male,0,1,Moderate,36.11,0,0,271.2,141,...,1.000000,Frequently,no,3.000000,no,1.000000,0.000000,Sometimes,Automobile,Overweight_Level_II
35,41,Male,0,1,Moderate,36.11,0,0,271.2,141,...,2.831771,Sometimes,no,1.725226,no,0.356288,0.000000,Sometimes,Automobile,Obesity_Type_II
36,41,Male,0,1,Moderate,36.11,0,0,271.2,141,...,2.701521,Sometimes,no,1.142644,no,0.514225,0.000000,no,Automobile,Obesity_Type_II
37,20,Male,1,0,Low,15.12,0,0,164.8,154,...,4.000000,Frequently,yes,2.000000,no,3.000000,2.000000,no,Public_Transportation,Normal_Weight
38,20,Male,1,0,Low,15.12,0,0,164.8,154,...,4.000000,Sometimes,no,3.000000,no,2.000000,2.000000,no,Public_Transportation,Insufficient_Weight
39,20,Male,1,0,Low,15.12,0,0,164.8,154,...,3.000000,Sometimes,no,2.000000,no,3.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
40,20,Male,1,0,Low,15.12,0,0,164.8,154,...,3.000000,Frequently,no,1.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
41,20,Male,1,0,Low,15.12,0,0,164.8,154,...,3.000000,Sometimes,yes,1.000000,no,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
42,20,Male,1,0,Low,15.12,0,0,164.8,154,...,3.000000,Sometimes,no,2.000000,no,1.000000,2.000000,no,Walking,Overweight_Level_II
43,20,Male,1,0,Low,15.12,0,0,164.8,154,...,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
44,20,Male,1,0,Low,15.12,0,0,164.8,154,...,3.000000,Sometimes,no,3.000000,yes,3.000000,0.000000,Sometimes,Automobile,Overweight_Level_I
45,20,Male,1,0,Low,15.12,0,0,164.8,154,...,1.000000,Frequently,no,3.000000,yes,2.000000,1.000000,no,Public_Transportation,Normal_Weight
46,20,Male,1,0,Low,15.12,0,0,164.8,154,...,3.000000,Frequently,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Obesity_Type_II
47,20,Male,1,0,Low,15.12,0,0,164.8,154,...,4.000000,Sometimes,no,3.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I
48,20,Male,1,0,Low,15.12,0,0,164.8,154,...,1.000000,Sometimes,no,3.000000,no,0.000000,0.000000,Frequently,Automobile,Overweight_Level_II
49,20,Male,1,0,Low,15.12,0,0,164.8,154,...,1.000000,Sometimes,no,2.000000,no,1.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight

In [97]:
merged_df.describe()

,Age,Smoking_x,Alcohol_Consumption,BMI,Diabetes,Hypertension,Cholesterol_Level,Resting_BP,Heart_Rate,Family_History_x,Fasting_Blood_Sugar,Exercise_Induced_Angina,Max_Heart_Rate_Achieved,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000,699071.000000
mean,24.394757,0.307223,0.401284,27.403755,0.198372,0.298167,224.811216,134.560438,94.742491,0.301698,0.150103,0.202872,149.731271,1.701697,87.971472,2.425586,2.679060,2.011304,0.989322,0.638418
std,6.243142,0.461343,0.490159,7.223686,0.398774,0.457454,43.500194,25.744273,20.085419,0.458995,0.357173,0.402138,28.832458,0.093070,25.972252,0.531291,0.766078,0.615700,0.843526,0.605555
min,18.000000,0.000000,0.000000,15.000000,0.000000,0.000000,150.000000,90.000000,60.000000,0.000000,0.000000,0.000000,100.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,20.000000,0.000000,0.000000,21.060000,0.000000,0.000000,186.900000,112.000000,78.000000,0.000000,0.000000,0.000000,125.000000,1.630000,68.818893,2.000000,2.669766,1.570188,0.112122,0.000000
50%,23.000000,0.000000,0.000000,27.330000,0.000000,0.000000,224.900000,135.000000,95.000000,0.000000,0.000000,0.000000,150.000000,1.700216,84.497980,2.392665,3.000000,2.000000,1.000000,0.585912
75%,26.000000,1.000000,1.000000,33.610000,0.000000,1.000000,262.500000,157.000000,112.000000,1.000000,0.000000,0.000000,175.000000,1.767479,108.934574,3.000000,3.000000,2.501638,1.612248,1.000000
max,61.000000,1.000000,1.000000,40.000000,1.000000,1.000000,300.000000,179.000000,129.000000,1.000000,1.000000,1.000000,199.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [105]:
merged_df.isna().sum().sum()

0